config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'


    resources :plans, only: [:new, :create, :show, :edit, :update, :index] do
      member do
        get 'check'
        patch 'status'
      end
      resources :days, only: [:new, :create, :edit, :update, :destroy] do
        resources :schedules, except: [:show, :index]
      end
    end
    
    get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :plan
  has_many :schedules, dependent: :destroy
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :days, dependent: :destroy

  enum prefecture:{
    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
    茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
    新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
    岐阜県:20,静岡県:21,愛知県:22,三重県:23,
    滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
    鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
    徳島県:35,香川県:36,愛媛県:37,高知県:38,
    福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45,
    沖縄県:46
  }

  enum stay_days:{
    日帰り:0,一泊二日:1,二泊三日:2,三泊四日:3,四泊～:4
  }

  enum budget:{
    "～1万":0,"1万～2万":1,"2万～3万":2,"3万～4万":3,"4万～5万":4,"5万～":5
  }

  enum main_vehicle:{
    自動車:0,公共交通機関:1,それ以外:2
  }

  has_many_attached :plan_images
  FILE_NUMBER_LIMIT = 5
  validate :validate_number_of_files

  private

  def validate_number_of_files
    return if plan_images.length <= FILE_NUMBER_LIMIT
    errors.add(:plan_images, "に添付できる画像は#{FILE_NUMBER_LIMIT}件までです。")
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :day

  enum transportation:{
    "移動手段":0,
    車:1,バス:1,電車:2,徒歩:3,自転車:4,その他:5
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

  def new
    @day = Day.new
  end

  def create
    plan = Plan.find(params[:plan_id])
    @day = Day.new(day_params)
    @day.plan_id = plan.id
    @day.save
    redirect_to new_plan_day_schedule_path(plan, @day)
  end

  def show
    @plan = Plan.find(params[:plan_id])
    @days = @plan.days
  end

  def edit
    @day = Day.find(params[:id])
    @plan = Plan.find(params[:plan_id])
  end

  def update
    plan = Plan.find(params[:plan_id])
    day = Day.find(params[:id])
    day.update(day_params)
    redirect_to check_plan_path(plan)
  end

  def destroy
  end


  private

  def day_params
    params.require(:day).permit(:number)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    if @plan.save
      redirect_to new_plan_day_path(@plan)
    else
      render :new
    end
  end

  def check
    @plan = Plan.find(params[:id])
    @days = @plan.days
  end

  def show
    @plan = Plan.find(params[:id])
    @days = @plan.days
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    plan = Plan.find(params[:id])
    plan.update(plan_params)
    redirect_to check_plan_path(plan)
  end

  def status
    plan = Plan.find(params[:id])
    days = plan.days
    days.each do |day|
      if (days != nil) && (day.schedules != nil)
        plan.update(plan_status: true)
        flash[:notice] = "投稿しました。"
        redirect_to plans_path
      else
        flash[:notice] = "未入力の欄があります。"
        render :show
      end
    end
  end

  def index
    @plans = Plan.all
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :prefecture, :stay_days, :budget, :main_vehicle, :impression, {plan_images: []})
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def new
    @schedule = Schedule.new
    @day = Day.find(params[:day_id])
    @schedules = @day.schedules
    @plan = Plan.find(params[:plan_id])
  end

  def create
    day = Day.find(params[:day_id])
    @schedule = Schedule.new(schedule_params)
    @schedule.day_id = day.id
    if @schedule.save
      redirect_to request.referer
    else
      render :new
    end
  end

  def index
    @schedules = Schedule.all
  end

  def edit
    @schedule = Schedule.find(params[:id])
    @day = Day.find(params[:day_id])
    @plan = Plan.find(params[:plan_id])
  end

  def update
    plan = Plan.find(params[:plan_id])
    schedule = Schedule.find(params[:id])
    schedule.update(schedule_params)
    redirect_to check_plan_path(plan)
  end

  def destroy
  end


  private

  def schedule_params
    params.require(:schedule).permit(:start_at, :finished_at, :place, :comment, :cost, :transportation, :transfer_time, :expense)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @plans = Plan.all
    @plans = @plans.where(prefecture: plan_params[:prefecture]) if plan_params[:prefecture].present?
    @plans = @plans.where(stay_days: plan_params[:stay_days]) if plan_params[:stay_days].present?
    @plans = @plans.where(budget: plan_params[:budget]) if plan_params[:budget].present?
    @plans = @plans.where(main_vehicles: plan_params[:main_vehicle]) if plan_params[:main_vehicle].present?
    @plans = @plans.where('title LIKE(?) or impression LIKE(?)',"%#{plan_params[:key_word]}%","%#{plan_params[:key_word]}%") if plan_params[:key_word].present?
  end


  private

  def plan_params
    params.permit(:prefecture, :stay_days, :budget, :main_vehicle, :title, :impression, :key_word)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/days/edit.html.erb
<div>
  <h1>日にち編集</h1>
  <%= form_with model: [@plan, @day], method: :patch do |f| %>
    <div class="form_group">
      <%= f.label :日にち %>
      <%= f.date_select :number, use_month_numbers: true %>
    </div>
    <div class="form_group">
      <%= f.submit "保存", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/days/new.html.erb
<div>
  <h1>日にち入力</h1>
  <%= form_with model: @day, url: plan_days_path do |f| %>
    <div class="form_group">
      <%= f.label :日にち %>
      <%= f.date_select :number, use_month_numbers: true %>
    </div>
    <div class="form_group">
      <%= f.submit "スケジュール入力", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<% if user_signed_in? %>
  <li>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  </li>
  <li>
    <%= link_to "Plan", new_plan_path %>
  </li>
<% else %>
  <li>
    <%= link_to "new", new_user_registration_path %>
  </li>
  <li>
    <%= link_to "Log in", new_user_session_path %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>X</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.select :prefecture, Plan.prefectures.keys, { include_blank: '都道府県'} %>
          <%= f.select :stay_days, Plan.stay_days.keys, { include_blank: '宿泊日数'} %>
          <%= f.select :budget, Plan.budgets.keys, { include_blank: '予算'} %>
          <%= f.select :main_vehicle, Plan.main_vehicles.keys, { include_blank: '移動手段'} %>
          <%= f.text_field :key_word, :placeholder => "キーワード" %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <!--<script src="application.js"></script>-->
  </body>
</html>

app/views/plans/check.html.erb
<div class="swiper">
  <div class="swiper-wrapper">
    <% if @plan.plan_images.attached? %>
    <div class="swiper-slide">
      <% @plan.plan_images.each do |image| %>
        <%= image_tag image, size: '200x200' %>
      <% end %>
    </div>
    <% end %>
  </div>
  <!-- ページネーションの要素 -->
   <div class="swiper-pagination"></div>
   <!-- ナビゲーションボタン （前、次） -->
   <div class="swiper-button-prev"><i class="fas fa-chevron-circle-left"></i></div>
   <div class="swiper-button-next"><i class="fas fa-chevron-circle-right ml-3"></i></div>
</div>  
    
<div>
  <p>
    タイトル<br><%= @plan.title %>
    <%= link_to "編集", edit_plan_path(@plan) %>
  </p>
</div>

<% @days.each do |day| %>
<div>
  <p>
    日にち<br><%= day.number %>
    <%= link_to "編集", edit_plan_day_path(@plan, day) %>
  </p>
  <p>
    スケジュール<br>
    <% day.schedules.each do |schedule| %>
      <%= schedule.start_at.strftime('%H:%M') %> ~
      <%= schedule.finished_at.strftime('%H:%M') %><br>
      <%= schedule.place %>
      <%= link_to "編集", edit_plan_day_schedule_path(@plan, day, schedule) %><br>
    <% end %>
  </p>
</div>
<% end %>

<p><%= link_to "投稿", status_plan_path(@plan), method: :patch %></p>

app/views/plans/edit.html.erb
<h2>プラン編集</h2>
<%= form_with model: @plan, method: :patch do |f| %>
  <div class="form_group">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>
  <div class="form_group">
    <%= f.label :都道府県 %>
    <%= f.select :prefecture, Plan.prefectures.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :宿泊日数 %>
    <%= f.select :stay_days, Plan.stay_days.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :予算 %>
    <%= f.select :budget, Plan.budgets.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :主な移動手段 %>
    <%= f.select :main_vehicle, Plan.main_vehicles.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :感想 %>
    <%= f.text_area :impression %>
  </div>
  <div class="form-group">
    <%= f.label :プラン画像 %>
    <%= f.file_field :plan_image, class: "form-control-file", accept: "image/*" %>
  </div>
  <div class="form-group">
    <%= f.submit "保存", class: "btn btn-info" %>
  </div>
<% end %>

app/views/plans/index.html.erb
<h1>プラン一覧</h1>

<div>
  <% @plans.each do |plan| %>
  <div>
    
    <% if plan.plan_images.attached? %>
      <% plan.plan_images.each do |image| %>
        <%= image_tag image, size: '200x200' %>
      <% end %>
    <% else %>
      <p>画像がありません</p>
    <% end %>
    
    <%= link_to plan_path(plan) do %>
      <%= plan.title %>
    <% end %>
    <%= plan.prefecture %>
    <%= plan.stay_days %>
    <%= plan.budget %>
    <%= plan.main_vehicle %>
    <%= plan.impression %>
  </div>
  <% end %>
</div>

app/views/plans/new.html.erb
<h2>プラン入力</h2>

<% if @plan.errors.any? %>
  <%= @plan.errors.count %>件のエラーが発生しました
  <ul>
    <% @plan.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @plan, method: :post do |f| %>
  <div class="form_group">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>
  <div class="form_group">
    <%= f.label :都道府県 %>
    <%= f.select :prefecture, Plan.prefectures.keys, { include_blank: '---'} %>
  </div>
  <div class="form_group">
    <%= f.label :宿泊日数 %>
    <%= f.select :stay_days, Plan.stay_days.keys, { include_blank: '---'} %>
  </div>
  <div class="form_group">
    <%= f.label :予算 %>
    <%= f.select :budget, Plan.budgets.keys, { include_blank: '---'} %>
  </div>
  <div class="form_group">
    <%= f.label :主な移動手段 %>
    <%= f.select :main_vehicle, Plan.main_vehicles.keys, { include_blank: '---'} %>
  </div>
  <div class="form_group">
    <%= f.label :感想 %>
    <%= f.text_area :impression %>
  </div>
  <div class="form-group">
    <%= f.label :プラン画像 %>
    <%= f.file_field :plan_images, multiple: true, class: "form-control-file", accept: "image/*" %>
  </div>
  <div class="form-group">
    <%= f.submit "日程入力", class: "btn btn-info" %>
  </div>
<% end %>

app/views/plans/show.html.erb
<div class="swiper">
  <div class="swiper-wrapper">
    <% if @plan.plan_images.attached? %>
      <% @plan.plan_images.each do |image| %>
      <div class="swiper-slide">
        <%= image_tag image, size: '200x200' %>
      </div>
      <% end %>
    <% end %>
  </div>
  <!-- ページネーションの要素 -->
   <div class="swiper-pagination"></div>
   <!-- ナビゲーションボタン （前、次） -->
   <div class="swiper-button-prev"><i class="fas fa-chevron-circle-left"></i></div>
   <div class="swiper-button-next"><i class="fas fa-chevron-circle-right ml-3"></i></div>
</div>  

<div>
  <p>
    タイトル<br><%= @plan.title %>
    <%= link_to "編集", edit_plan_path(@plan) %>
  </p>
</div>

<% @days.each do |day| %>
<div>
  <p>
    日にち<br><%= day.number %>
    <%= link_to "編集", edit_plan_day_path(@plan, day) %>
  </p>
  <p>
    スケジュール<br>
    <% day.schedules.each do |schedule| %>
      <%= schedule.start_at.strftime('%H:%M') %> ~
      <%= schedule.finished_at.strftime('%H:%M') %><br>
      <%= schedule.place %>
      <%= link_to "編集", edit_plan_day_schedule_path(@plan, day, schedule) %><br>
    <% end %>
  </p>
</div>
<% end %>

app/views/schedules/edit.html.erb
<h1>スケジュール編集</h1>
<%= form_with model: [@plan, @day, @schedule], method: :patch do |f| %>
  <div class="form_group">
    <%= f.label :開始時刻 %>
    <%= f.time_select :start_at, {} %>
  </div>
  <div class="form_group">
    <%= f.label :終了時刻 %>
    <%= f.time_select :finished_at, {} %>
  </div>
  <div class="form_group">
    <%= f.label :場所 %>
    <%= f.text_field :place %>
  </div>
  <div class="form_group">
    <%= f.label :コメント %>
    <%= f.text_area :comment %>
  </div>
  <div class="form_group">
    <%= f.label :費用 %>
    <%= f.text_field :cost %>円
  </div>
  <div class="form_group">
    <%= f.label :移動手段 %>
    <%= f.select :transportation, Schedule.transportations.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :移動時間 %>
    <%= f.text_field :transfer_time %>分
  </div>
  <div class="form_group">
    <%= f.label :交通費 %>
    <%= f.text_field :expense %>円
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/schedules/new.html.erb
<h1><%= @day.number %>のスケジュール</h1>

<div>
  <% @schedules.each do |schedule| %>
  <div>
    <%= schedule.start_at.strftime('%H:%M') %> ~
    <%= schedule.finished_at.strftime('%H:%M') %>
    <%= schedule.place %>
    <%= schedule.comment %>
    <%= schedule.cost %>円
    <%= schedule.transportation %>
    <%= schedule.transfer_time %>分
    <%= schedule.expense %>円
  </div>
  <% end %>
</div>

<%= form_with model: @schedule, url: plan_day_schedules_path do |f| %>
  <div class="form_group">
    <%= f.label :開始時刻 %>
    <%= f.time_select :start_at, {} %>
  </div>
  <div class="form_group">
    <%= f.label :終了時刻 %>
    <%= f.time_select :finished_at, {} %>
  </div>
  <div class="form_group">
    <%= f.label :場所 %>
    <%= f.text_field :place %>
  </div>
  <div class="form_group">
    <%= f.label :コメント %>
    <%= f.text_area :comment %>
  </div>
  <div class="form_group">
    <%= f.label :費用 %>
    <%= f.text_field :cost %>円
  </div>
  <div class="form_group">
    <%= f.label :移動手段 %>
    <%= f.select :transportation, Schedule.transportations.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :移動時間 %>
    <%= f.text_field :transfer_time %>分
  </div>
  <div class="form_group">
    <%= f.label :交通費 %>
    <%= f.text_field :expense %>円
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

<div>
  <%= link_to "日程追加", new_plan_day_path %>|
  <%= link_to "確認画面", check_plan_path(@plan) %>
</div>

app/views/searches/search.html.erb
<h1>結果</h1>
<% @plans.each do |plan| %>
  <%= plan.title %>
<% end %>